Bump Jetty server 12.0.22 to align Kafka one (fix tests with NoSuchMethodError exception) due to old 12.0.16
Signed-off-by: Paolo Patierno <ppatierno@live.com>