Add support Apache Kafka 4.1.0 RC0
Signed-off-by: Paolo Patierno <ppatierno@live.com>

Add support Apache Kafka 4.1.0 RC1

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Bump Jetty server 12.0.22 to align Kafka one (fix tests with NoSuchMethodError exception) due to old 12.0.16

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Fix upgrade/downgrade tests

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Fixed downgrade test

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Fixed KafkaRoller not able to dynamically update min.insync.replicas
when ELR is enabled

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Revert "Fixed KafkaRoller not able to dynamically update min.insync.replicas when ELR is enabled"

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Fixed new lines

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Add support Apache Kafka 4.1.0 RC2

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Fix tests overwriting min.insync.replicas

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Add support Apache Kafka 4.1.0 RC3

Signed-off-by: Paolo Patierno <ppatierno@live.com>